// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZCw74aicbZWWo0YtaNuMgFQesRHAElsw',
    appId: '1:721835234572:web:4ff925af4c3fb50776e529',
    messagingSenderId: '721835234572',
    projectId: 'grameen-light-5403b',
    authDomain: 'grameen-light-5403b.firebaseapp.com',
    storageBucket: 'grameen-light-5403b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgVer16WnSm5w4YAr77mih8-xIWxIpYgw',
    appId: '1:721835234572:ios:035b3edd5e1484c476e529',
    messagingSenderId: '721835234572',
    projectId: 'grameen-light-5403b',
    storageBucket: 'grameen-light-5403b.firebasestorage.app',
    iosBundleId: 'com.example.grameenLight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgVer16WnSm5w4YAr77mih8-xIWxIpYgw',
    appId: '1:721835234572:ios:035b3edd5e1484c476e529',
    messagingSenderId: '721835234572',
    projectId: 'grameen-light-5403b',
    storageBucket: 'grameen-light-5403b.firebasestorage.app',
    iosBundleId: 'com.example.grameenLight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZCw74aicbZWWo0YtaNuMgFQesRHAElsw',
    appId: '1:721835234572:web:a08158ee8f22630776e529',
    messagingSenderId: '721835234572',
    projectId: 'grameen-light-5403b',
    authDomain: 'grameen-light-5403b.firebaseapp.com',
    storageBucket: 'grameen-light-5403b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCslVvf_3ea1dHfYweUwP0i0dCFomkyZBI',
    appId: '1:721835234572:android:fc594a09db20e5e676e529',
    messagingSenderId: '721835234572',
    projectId: 'grameen-light-5403b',
    storageBucket: 'grameen-light-5403b.firebasestorage.app',
  );

}